stages:
  - build
  - test

frontend:
  image: node:22-alpine
  stage: build
  script:
    - cd frontend/fatura
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/fatura/dist/

backend:
  image: node:22-alpine
  stage: build
  script:
    - cd backend
    - npm install

frontend-test:
  image: node:22-alpine
  stage: test
  script:
    - test -f frontend/fatura/dist/index.html

unit-tests:
  image: node:22-alpine
  stage: test
  script:
    - cd backend
    - npm ci
    - npm test
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit: ./backend/junit.xml
