stages:
  - build

frontend:
  image: node:22-alpine
  stage: build
  script:
    - cd frontend/fatura
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - cd frontend/fatura
      - dist/

backend:
  image: node:22-alpine
  stage: build
  script:
    - cd backend
    - npm install
